/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EventManagerAbi } from "./EventManagerAbi";

export { EventManagerAbi__factory } from "./factories/EventManagerAbi__factory";
